import Wraper from '@/components/Wraper'
import './globals.css'
import './globalsSwiper.css'
import "bootstrap/dist/css/bootstrap.min.css"


export const metadata = {
  title: 'Internsala Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Wraper children={children}></Wraper>
        </body>
    </html>
  )
}
